theme: jekyll-theme-slate
markdown: kramdown
title: Maya W.'s Engineering Portfolio
description: This website serves as documentation of my time with Bluestamp Engineering, in which I constructed a fully-functional automated cat laser.
