theme: jekyll-theme-midnight
markdown: kramdown
title: Automated Cat Laser
description: Store-bought lasers are overrated...handbuilt ones are so much cooler and assembling them provides a great learning experience!
